#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
protocolport: 20870
applicationName: warehouse-service
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze35w2s039360x3w7o.mysql.rds.aliyuncs.com:3306/clms_werehouse_db?characterEncoding=utf-8&useSSL=false
    username: clms_root
    password: clMs201801#@01&
    druid:
      initial-size: 6
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
    name: warehouse-db
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:/com/lcdt/warehouse/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lcdt.warehouse.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
#    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 8071
logging:
  file: ${user.dir}/log/warehouse-service.log

